#!/usr/bin/env python3
"""Re-run the indicator confirmation on a body-direct artifact's retained candidates.

``artifacts/phase1-body-direct-sweep-v1.json`` was produced before 9c6bfb7
("Recover the ring setting before the indicator confirmation"), so its
``indicator_confirmation`` fields scored every candidate under the held rings.
The sweep scores and the retained plugboards are unaffected; only the
confirmation stage changed.  This script takes the retained candidates exactly as
recorded and re-scores them with the current confirmation, which recovers every
ring setting compatible with the swept body, and writes a supplementary artifact
next to the original.  The original is left as the record of what the run
produced.

    python3 scripts/reconfirm_body_direct.py

It costs a few seconds, not a sweep, so it is regenerated by the artifact check.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import pathlib
import statistics
import sys
from typing import Any

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import enigma_fast  # noqa: E402
import phase1_stecker as stecker  # noqa: E402
from provenance import code_version, sha256_file  # noqa: E402
from stecker_controls import confirm_against_date  # noqa: E402
from stecker_scoring import FastNgramScorer  # noqa: E402
from stecker_traffic import traffic_from_corpus  # noqa: E402

SCHEMA = "enigma-attack.phase1-body-direct-reconfirmation/v1"
DEFAULT_SOURCE = "artifacts/phase1-body-direct-sweep-v1.json"
DEFAULT_CONFIG = "experiments/phase1-body-direct-sweep-v1/config.json"
DEFAULT_OUTPUT = "artifacts/phase1-body-direct-sweep-v1-reconfirmation.json"


def letters(text: str) -> tuple[int, ...]:
    return tuple(ord(letter) - 65 for letter in text)


def reconfirm(source: dict[str, Any], config: dict[str, Any]) -> dict[str, Any]:
    scorer = FastNgramScorer(config["scorer"])
    reflector = enigma_fast.reflector_table(config["machine"]["reflector"])
    traffic = traffic_from_corpus(
        stecker.resolve_path(config["corpus"]),
        config["target"]["date"],
        config["target"]["messages"],
    )
    message = {row.designator: row for row in traffic}[source["result"]["message"]]
    rows: list[dict[str, Any]] = []
    for candidate in source["result"]["top_candidates"]:
        confirmation = confirm_against_date(
            traffic,
            enigma_fast.plugboard_table(candidate["plugboard"]),
            candidate["rotor_order_left_to_right"],
            letters(candidate["rings"]),
            scorer,
            reflector,
            config["indicator_orderings"],
            swept_message=message,
            swept_start=letters(candidate["start_position"]),
        )
        rows.append(
            {
                "rank": candidate["rank"],
                "score_per_letter": candidate["score_per_letter"],
                "rotor_order_left_to_right": candidate["rotor_order_left_to_right"],
                "start_position": candidate["start_position"],
                "plugboard": candidate["plugboard"],
                "held_rings_confirmation_score": candidate["indicator_confirmation"][
                    "best_pooled_score_per_letter"
                ],
                "indicator_confirmation": confirmation,
            }
        )
    scores = [row["indicator_confirmation"]["best_pooled_score_per_letter"] for row in rows]
    gains = [
        row["indicator_confirmation"]["best_pooled_score_per_letter"] - row["score_per_letter"]
        for row in rows
    ]
    return {
        "candidates": len(rows),
        "best_pooled_score_per_letter": max(scores),
        "mean_pooled_score_per_letter": round(statistics.fmean(scores), 9),
        "candidates_with_a_compatible_ring_setting": sum(
            1 for row in rows if row["indicator_confirmation"]["compatible_ring_settings"]
        ),
        "candidates_scoring_above_their_own_sweep_score": sum(1 for gain in gains if gain > 0),
        "best_gain_over_sweep_score": round(max(gains), 9),
        "superseded_source_fields": {
            "best_pooled_score_per_letter": source["result"]["indicator_confirmation"][
                "best_pooled_score_per_letter"
            ],
            "mean_pooled_score_per_letter": source["result"]["indicator_confirmation"][
                "mean_pooled_score_per_letter"
            ],
            "reason": (
                "Scored under the held rings AAA. The sweep absorbs the left and "
                "middle rings into the start position, so the held value is the "
                "parameterization, not the daily key, and deciphering the "
                "indicator under it tests the wrong key (fixed in 9c6bfb7)."
            ),
        },
        "interpretation_rule": (
            "A candidate that is the daily key gains the companion messages' "
            "letters when its plugboard and a compatible ring setting are fed "
            "through the clear indicator, so its pooled score per letter should "
            "rise toward the positive controls (about -6.7). A wrong candidate's "
            "pooled score falls toward the wrong-key null (about -8.9 or below)."
        ),
        "top_candidates": rows,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--source", default=DEFAULT_SOURCE)
    parser.add_argument("--config", default=DEFAULT_CONFIG)
    parser.add_argument("--output", default=DEFAULT_OUTPUT)
    arguments = parser.parse_args(argv)

    version = code_version()
    started_at = dt.datetime.now(dt.timezone.utc)
    source_path = stecker.resolve_path(arguments.source)
    config_path = stecker.resolve_config(arguments.config)
    source = json.loads(source_path.read_text(encoding="utf-8"))
    config = stecker.load_config(config_path)
    result = reconfirm(source, config)
    payload = {
        "schema": SCHEMA,
        "experiment_id": f"{source['experiment_id']}-reconfirmation",
        "started_at": started_at.isoformat(),
        "completed_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "source_artifact": {
            "path": stecker.describe_path(source_path),
            "sha256": sha256_file(source_path),
            "recorded_code_sha256": source.get("inputs", {}).get("code_sha256"),
        },
        "configuration": {
            "path": stecker.describe_path(config_path),
            "sha256": sha256_file(config_path),
        },
        "code": version,
        "inputs": {"corpus_sha256": sha256_file(stecker.resolve_path(config["corpus"]))},
        "result": result,
    }
    output = pathlib.Path(arguments.output)
    if not output.is_absolute():
        output = ROOT / output
    output.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(
        f"{result['candidates']} candidates: best {result['best_pooled_score_per_letter']:.3f}, "
        f"mean {result['mean_pooled_score_per_letter']:.3f}, "
        f"{result['candidates_with_a_compatible_ring_setting']} with a compatible ring setting, "
        f"{result['candidates_scoring_above_their_own_sweep_score']} above their sweep score"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
